[project]
name = "Decentralized-agricultural-insurance-parametric"
telemetry = false
cache_dir = "./.cache"
[contracts.weather-trigger-payout-engine]
path = "contracts/weather-trigger-payout-engine.clar"
[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
