[project]
name = 'Decentralized-agricultural-insurance-parametric'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.weather-trigger-payout-engine]
path = 'contracts/weather-trigger-payout-engine.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
